@startwbs

title Space Engineers (Subset) Progression Tree

+ Progression
++ Basic Assembler
+++ Battery
++++ Control Panel
++++ Button Panel (Group)
++++ Piston (Group)
++++ Rotor (Group)
++++ Hinge (Group)
++++ Camera
++++ Beacon
+++++ Antenna
++++++ Laser Antenna 
++++ Door (Group)
+++ Medical Room 
+++ Spot Light (group)
+++ Interior Light
++++ Projector
++++ AI Flight (Group)
+++++ AI Recorder {Task}
+++++ AI Basic {Task}
+++++ AI Flight {Task}
+++++ AI Defensive {Task}
+++++ AI Offensive {Task}
++++ LCDs
++++ Sensor 
++++ Programmable Block (Group)
++++ Timer Block
++++ Event Controller
++++ Window (Group)
+++ Assembler
++++ Rocket Launcher (Group)
+++++ Railgun
+++++ Artillery
+++++ Assault Gun
++++ Gatling Gun
+++++ Decoy
++++ Speed Module (Group)
++++ Power Module
++++ Yield Module
++++ Gravity Generator
+++++ Jump Drive
+++++ Artificial Mass
++ Light Armor Block (Group)
++ Interior Wall (Group)
+++ Ladder
+++ Catwalks
+++ Ramps
+++ Grated Catwalks (Group) <Warfare>
+++ Railing Straight (Group) <Warfare>
++ Basic Refinery
+++ Ore Detector
+++ Drill
+++ Refinery (Group)
++++ Speed Module (Group)
++++ Power Module
++++ Yield Module
++++ Reactor (Group)
+++++ Warhead
++ Landing Gear (Group)
+++ Seat
+++ Wheels (Group)
+++ Parachute
+++ Control Station (Group)
+++ Cockpit (Group)
++++ Small Grid Gatling Gun
++++ Thrusters Atmospheric (Group)
++++ Thrusters Hydrogen (Group)
++++ Thrusters Ion (Group)
++++ Gyrscope
++++ Grinder (Group)
++++ Welder
++++ Drill
++++ Small Grid Rocket Launcher
++ Oxygen Farm
++ H2/O2 Generator
+++ Oxygen Tank (Group)
+++ Cryo Chamber
+++ Air Vent
+++ Hydrogen Engine 
++ Cargo Container (Group)
+++ Small Grid Conveyor (Group)
+++ Conveyor (Group)
++++ Reinforced Conveyor Tube (Group)
++++ Collector (Group)
++++ Connector
++++ Ejector
++++ Small Grid Connector
++++ Conveyor Sorter
++ Solar Panel
++ Wind Turbine
+++ Merge Block
@endwbs
